name: Check PR Labels

on:
  pull_request_target:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          github-token: ${{ github.token }}
          valid-labels: 'bug, dependencies, devops, enhancement, feature, tests, documentation'
          pull-request-number: ${{ github.event.pull_request.number }}
